### ISSUE TITLE
Python3.7+: RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by rsirres** [verterok/tritcask#3]
Tritcask is unable to iterate over TritcaskEntries as a StopIterator is raise within a generator.
With Python3.7+ and according to [PEP 479](https://www.python.org/dev/peps/pep-0479/) this is longer allowed. 

A simple fix would be to replace `StopIteration` Exception with a `return` statement.

``` 
$ python3 -V
Python 3.7.4
$ python3 benchmark.py 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tritcask/tritcask.py", line 496, in iter_entries
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "benchmark.py", line 42, in <module>
    db = tritcask.Tritcask(db_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tritcask/tritcask.py", line 654, in __init__
    self._build_keydir()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tritcask/tritcask.py", line 802, in _build_keydir
    self._load_from_hint(data_file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tritcask/tritcask.py", line 817, in _load_from_hint
    for hint_entry in hint_file.iter_entries():
RuntimeError: generator raised StopIteration`

**Comment by verterok** [comment]
Hi,
Thanks for reporting the problem. Will try to get the fix pushed in the next days.

Regards
